### ISSUE TITLE
PyGSTi incompatibility: `Label` and `todense` not needed in `compatibility.py`

### ISSUE THREAD

**Issue by quantshah** [rabrie/mGST#2]
Hi, thanks for the nice code implementation. I am interested in different QPT schemes and I am working on benchmarking various QPT implementations such as [pyGST](https://zenodo.org/badge/DOI/10.5281/zenodo.5546759.svg) vs [QPT-PLS](https://github.com/qutip/qutip-notebooks/blob/241f77edd9f3f821da715959d5ee1c6eaada7f78/examples/tomography-process-tomo-pls.ipynb). 

Using the latest pyGSTi installation with `pip install pygsti`, I had to change two things in `compatibility.py` before I could run your code. The import statement for `Label` could be removed. In line 35 and 36, the `todense()` call can be removed. I can open a PR to make these changes so that the code works with the latest pyGSTi version.

I am also interested in making a package out of your code so that it is installable using pip and writing a tutorial about it in QuTiP similar to the one for [QPT-PLS](https://github.com/qutip/qutip-notebooks/blob/241f77edd9f3f821da715959d5ee1c6eaada7f78/examples/tomography-process-tomo-pls.ipynb). 

Details below:

------------------------------------------------------------------------------------------------------------------------

I think the Label class is not used anywhere in the `compatibility.py` file. So it was safe to remove it to run the tutorial. 

```
      2 import pygsti
      3 from pygsti.report import reportables as rptbl
----> 4 from pygsti.objects import Label
      5 from pygsti.tools import change_basis
      6 

ModuleNotFoundError: No module named 'pygsti.objects'
```

Also, in line 35 and 36 of `compatibility.py` the `todense` method does not work as pyGSTi seems to have changed behaviour so the following gives an error:

```
      1 from pygsti.modelpacks import smq1Q_XYI as std
      2 mdl_datagen = std.target_model().depolarize(0.01).randomize_with_unitary(0.01)   # use pygsti-function to add noise
----> 3 X_true, E_true, rho_true = pygsti_model_to_arrays(mdl_datagen, basis = 'std')   # turn pygsti model object into numpy arrays
      4 
      5 pdim = 2

~/Dropbox/phd/process-tomography/mGST/mGST/compatibility.py in pygsti_model_to_arrays(model, basis)
     33     op_Labels = [label for label in model.__dict__['operations'].keys()]
     34     effect_Labels = [label for label in model['Mdefault'].keys()]
---> 35     E = np.array([model['Mdefault'][label].todense().reshape(-1) for label in effect_Labels])
     36     rho = model['rho0'].todense().reshape(-1)
     37     for op_Label in op_Labels:

~/Dropbox/phd/process-tomography/mGST/mGST/compatibility.py in <listcomp>(.0)
     33     op_Labels = [label for label in model.__dict__['operations'].keys()]
     34     effect_Labels = [label for label in model['Mdefault'].keys()]
---> 35     E = np.array([model['Mdefault'][label].todense().reshape(-1) for label in effect_Labels])
     36     rho = model['rho0'].todense().reshape(-1)
     37     for op_Label in op_Labels:

~/miniconda3/envs/mgst/lib/python3.9/site-packages/pygsti/modelmembers/povms/conjugatedeffect.py in __getattr__(self, attr)
     85         #use __dict__ so no chance for recursive __getattr__
     86         if '_rep' in self.__dict__:  # sometimes in loading __getattr__ gets called before the instance is loaded
---> 87             ret = getattr(self.columnvec, attr)
     88         else:
     89             raise AttributeError("No attribute:", attr)

AttributeError: 'numpy.ndarray' object has no attribute 'todense'
```

**Comment by rabrie** [comment]
Hi!
Thanks for informing me about these issues, I just updated the file 'compatibility.py' to work with the latest version of pygsti. 

If you have any questions regarding the implementation or if I can help with the package/tutorial just let me know.
